name: List affected rockspecs

on:
  workflow_call:
    outputs:
      rockspecs:
        value: ${{ jobs.affected.outputs.rockspecs }}

jobs:
  affected:
    name: Find edited rockspecs
    runs-on: ubuntu-20.04
    outputs:
      rockspecs: '["${{ steps.changed-files.outputs.all_modified_files }}"]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: changed-files
        uses: tj-actions/changed-files@v18
        with:
          files: |
            *.rockspec
            rockspecs/*.rockspec
          separator: '", "'
